### ISSUE TITLE
if password Command not send  irc is bug

### ISSUE THREAD

**Issue by yuki-shimoda-crypto** [sora-grayscale/ft_irc#191]
passが間違っているときにirssiで使うとバグります

**Comment by sora-grayscale** [comment]
間違うと永遠に同じPASSがirssiから送られてきて壊れるから一度でも間違ったパスワードが来ると接続を終了するようにしています。

**Comment by yuki-shimoda-crypto** [comment]
PASSコマンドをなしでやるとバグるので、それの対応をします。
また、一回間違った場合に接続終了はあまりにもきついので3回とかにします
