### ISSUE TITLE
Create Command Nick message

### ISSUE THREAD

**Issue by yuki-shimoda-crypto** [sora-grayscale/ft_irc#39]

**Comment by sora-grayscale** [comment]
# NICK command
## 入力形式
```
Command: NICK
Parameters: <nickname>
```

### 説明
- NICK コマンドは、ユーザにニックネームを与えたり、既存のニックネームを変更するために使用されます。
(IMO)

## 返答
### Error時
```
ERR_NONICKNAMEGIVEN
ERR_ERRONEUSNICKNAME
ERR_NICKNAMEINUSE
ERR_NICKCOLLISION
ERR_UNAVAILRESOURCE
ERR_RESTRICTED
```

### Success時
- 記述なし

## 入力例
```
NICK Wiz
    ; セッションが未登録の場合、新しいニックネーム "Wiz" を導入、
      またはユーザがニックネームを "Wiz" に変更した場合。


:WiZ!jto@tolsun.oulu.fi NICK Kilroy
    ; WiZ が Kilroy にニックネームを変更したことを伝えるサーバ。

```

## 参考
[2812 3.1.2 Nick メッセージ](https://solareenlo.com/rfc2812/message-details/nick-message.html#312-nick-%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8)
