### ISSUE TITLE
Create Command User message

### ISSUE THREAD

**Issue by yuki-shimoda-crypto** [sora-grayscale/ft_irc#40]

**Comment by sora-grayscale** [comment]
# User command
## 入力形式
```
Command: USER
Parameters: <user> <mode> <unused> <realname>
```

### 説明
- USER コマンドは、接続の最初に使用し、新規ユーザのユーザ名、ホスト名、リアルネームを指定します。
    - user: 
        > user       =  1*( %x01-09 / %x0B-0C / %x0E-1F / %x21-3F / %x41-FF )
        >             ; any octet except NUL, CR, LF, " " and "@"
        - 1文字以上
        - NULL,CR,LF," ",@以外のascii文字
    - mode: 
    - modeコマンドを呼ぶ感じ→つまりUser::setmodeするだけ
    > \<mode> パラメータには数値を指定し、サーバに登録する際にユーザモードを自動的に設定することができます。このパラメータはビットマスクで、2ビットだけが意味を持ちます。ビット2が設定されるとユーザモード w が設定され、ビット3が設定されるとユーザモード i が設定されます。（[3.1.5 User Mode メッセージ](https://solareenlo.com/rfc2812/message-details/user-mode-message.html) を参照）。
    - unused: 
    - realname: 
    > <realname> には空白文字が含まれることがあります。

(IMO)

## 返答
### Error時
```
ERR_NEEDMOREPARAMS
ERR_ALREADYREGISTRED

```


### Success時
```
記述なし
```

## 入力例
```
USER guest 0 * :Ronnie Reagan
    ; ユーザ名 "guest"、本名 "Ronnie Reagan" で登録したユーザ。

USER guest 8 * :Ronnie Reagan
    ; ユーザ名 "guest"、本名 "Ronnie Reagan" で登録し、非表示にすることを依頼するユーザ。

```

## 参考
[2812 3.1.3 Userメッセージ](https://solareenlo.com/rfc2812/message-details/user-message.html)
