### ISSUE TITLE
Create Command Motd message

### ISSUE THREAD

**Issue by yuki-shimoda-crypto** [sora-grayscale/ft_irc#59]

**Comment by sora-grayscale** [comment]
Command: MOTD
Parameters: [ <target> ]
MOTD コマンドは、指定されたサーバ（<target> が省略された場合は現在のサーバ）の "今日のメッセージ" を取得するために使用されます。

<target> パラメータには、ワイルドカードを使用できます。

数値返信：


        RPL_MOTDSTART                   RPL_MOTD
        RPL_ENDOFMOTD                   ERR_NOMOTD

375    RPL_MOTDSTART
       ":- <server> Message of the day - "
372    RPL_MOTD
       ":- <text>"
376    RPL_ENDOFMOTD
       ":End of MOTD command"
422    ERR_NOMOTD
      ":MOTD File is missing"
サーバーの MOTD ファイルを開くことができませんでした。
