### ISSUE TITLE
Create Command Time message

### ISSUE THREAD

**Issue by yuki-shimoda-crypto** [sora-grayscale/ft_irc#64]

**Comment by sora-grayscale** [comment]
391    RPL_TIME
       "<server> :<string showing server's local time>"
TIME メッセージに返信する場合、サーバは上記の RPL_TIME 形式を使用して返信を送信する必要があります。時刻を示す文字列は、そこに正しい曜日と時刻を含むだけでよいです。時刻を示す文字列には、それ以上の要件はありません。
