### ISSUE TITLE
Create Command Admin command

### ISSUE THREAD

**Issue by yuki-shimoda-crypto** [sora-grayscale/ft_irc#67]

**Comment by sora-grayscale** [comment]
256    RPL_ADMINME
       "<server> :Administrative info"
257    RPL_ADMINLOC1
       ":<admin info>"
258    RPL_ADMINLOC2
       ":<admin info>"
259    RPL_ADMINEMAIL
       ":<admin info>"
ADMIN メッセージに返信する場合、サーバは RPL_ADMINME から RPL_ADMINEMAIL までの返信を使用し、それぞれにテキストメッセージを提供することが期待されています。RPL_ADMINLOC1 には、サーバがある都市、州、国の説明が期待され、次に機関の詳細 RPL_ADMINLOC2、最後にサーバの管理連絡先 RPL_ADMINEMAIL にはメールアドレスが必要です。
